export const door = {
    "doorOne":{
        height_diff:270,
        scene:"./public/assets/medieval_door/scene.gltf",
        scaleX:0.003,
        scaleY:0.003,
        scaleZ:0.003,
        positionX:0, 
        positionY:0,
        positionZ:39,
    },
    "doorTwo":{
        height_diff:270,
        scene:"./public/assets/old_wooden_door/scene.gltf",
        scaleX:0.003,
        scaleY:0.003,
        scaleZ:0.003,
        positionX:0, 
        positionY:0,
        positionZ:2
    },
}